/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaAsistencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mycomputer
 */
public class ConsultaNomina extends javax.swing.JFrame {

    Modelo.Conexion cc = new Modelo.Conexion();
    Connection cn = cc.getConnection();
    private Modelo.Conexion db = new Modelo.Conexion();
    Statement sent;
    ResultSet conjuntoResultados;
    private Object[][] dtcliente;
    
    /**
     * Creates new form HoraPorDia
     */
    public ConsultaNomina() {
        initComponents();
        LlenarTablaNomina();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Consultar nómina");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        btnGenNomina = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menuEmpleado = new javax.swing.JMenu();
        verPrincipal = new javax.swing.JMenuItem();
        menuEmpleado1 = new javax.swing.JMenu();
        verEmpleado = new javax.swing.JMenuItem();
        menuHora = new javax.swing.JMenu();
        menuHoraEntrada = new javax.swing.JMenuItem();
        menuHoraSalida = new javax.swing.JMenuItem();
        consultaDia = new javax.swing.JMenuItem();
        Nómina = new javax.swing.JMenu();
        GenerarNomina = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        generaReporteEmpleado = new javax.swing.JMenuItem();
        generaReporteHoras = new javax.swing.JMenuItem();
        generaReporteNomina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaConsulta);

        btnGenNomina.setText("Generar nómina");
        btnGenNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenNominaActionPerformed(evt);
            }
        });

        menuEmpleado.setText("Inicio");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });

        verPrincipal.setText("Ir a ventana de inicio");
        verPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrincipalActionPerformed(evt);
            }
        });
        menuEmpleado.add(verPrincipal);

        Menu.add(menuEmpleado);

        menuEmpleado1.setText("Empleado");
        menuEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleado1ActionPerformed(evt);
            }
        });

        verEmpleado.setText("Ir a ventana de empleados");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado1.add(verEmpleado);

        Menu.add(menuEmpleado1);

        menuHora.setText("Hora");

        menuHoraEntrada.setText("Registrar hora de entrada");
        menuHoraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraEntradaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraEntrada);

        menuHoraSalida.setText("Registrar hora de salida");
        menuHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraSalidaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraSalida);

        consultaDia.setText("Consultar horas por día");
        consultaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDiaActionPerformed(evt);
            }
        });
        menuHora.add(consultaDia);

        Menu.add(menuHora);

        Nómina.setText("Nómina");

        GenerarNomina.setText("Generar nómina");
        GenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarNominaActionPerformed(evt);
            }
        });
        Nómina.add(GenerarNomina);

        Menu.add(Nómina);

        jMenu1.setText("Reportes");

        generaReporteEmpleado.setText("Generar reporte de los empleados");
        generaReporteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteEmpleado);

        generaReporteHoras.setText("Generar reporte de horas de entrada y salida");
        generaReporteHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteHorasActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteHoras);

        generaReporteNomina.setText("Generar reporte de nómina");
        generaReporteNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteNominaActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteNomina);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(btnGenNomina)
                .addGap(453, 453, 453))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGenNomina)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void LlenarTablaNomina(){
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre","Sueldo pagado"};        
        dtcliente = db.SelectNomina();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtcliente,columNames);
        TablaConsulta.setRowHeight(30);
        TablaConsulta.setModel(datos);
    }
    
    private void verPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrincipalActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.Principal obj = new VentanaAsistencia.Principal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_verPrincipalActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuHoraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraEntradaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.AltaHoraEntrada obj = new VentanaAsistencia.AltaHoraEntrada();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_menuHoraEntradaActionPerformed

    private void menuHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraSalidaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.AltaHoraSalida obj = new VentanaAsistencia.AltaHoraSalida();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_menuHoraSalidaActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.ConsultaEmpleado obj = new VentanaAsistencia.ConsultaEmpleado();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void menuEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleado1ActionPerformed

    private void consultaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDiaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.HoraPorDia obj = new VentanaAsistencia.HoraPorDia();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_consultaDiaActionPerformed

    private void GenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarNominaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.GeneraNomina obj = new VentanaAsistencia.GeneraNomina();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_GenerarNominaActionPerformed

    private void btnGenNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenNominaActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.GeneraNomina obj = new VentanaAsistencia.GeneraNomina();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGenNominaActionPerformed

    private void generaReporteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteEmpleadoActionPerformed
        // TODO add your handling code here:
        Modelo.Conexion cc = new Modelo.Conexion();
        String path = "C://Users/mycomputer/Documents/NetBeansProjects/Asistencias/src/Reportes/reporteEmpleado.jasper";
        JasperReport jr = null;
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cc.getConnection());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Reporte de empleados");

        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_generaReporteEmpleadoActionPerformed

    private void generaReporteHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteHorasActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.BuscarNombre obj = new VentanaAsistencia.BuscarNombre();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_generaReporteHorasActionPerformed

    private void generaReporteNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteNominaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.BuscarNomina obj = new VentanaAsistencia.BuscarNomina();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_generaReporteNominaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GenerarNomina;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Nómina;
    private javax.swing.JTable TablaConsulta;
    private javax.swing.JButton btnGenNomina;
    private javax.swing.JMenuItem consultaDia;
    private javax.swing.JMenuItem generaReporteEmpleado;
    private javax.swing.JMenuItem generaReporteHoras;
    private javax.swing.JMenuItem generaReporteNomina;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuEmpleado1;
    private javax.swing.JMenu menuHora;
    private javax.swing.JMenuItem menuHoraEntrada;
    private javax.swing.JMenuItem menuHoraSalida;
    private javax.swing.JMenuItem verEmpleado;
    private javax.swing.JMenuItem verPrincipal;
    // End of variables declaration//GEN-END:variables
}
