/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaAsistencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mycomputer
 */
public class GeneraNomina extends javax.swing.JFrame {

    Modelo.Conexion cc = new Modelo.Conexion();
    Connection cn = cc.getConnection();
    private Modelo.Conexion db = new Modelo.Conexion();
    Statement sent;
    ResultSet conjuntoResultados;
    private Object[][] dtcliente;
    
    /**
     * Creates new form HoraPorDia
     */
    public GeneraNomina() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Generar nómina");
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreBuscar = new javax.swing.JComboBox();
        buscFecha = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        descRetardo = new javax.swing.JTextField();
        descFalta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPagar = new javax.swing.JTextField();
        txtRetardo = new javax.swing.JComboBox();
        txtFalta = new javax.swing.JComboBox();
        borrar = new javax.swing.JButton();
        idEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menuEmpleado = new javax.swing.JMenu();
        verPrincipal = new javax.swing.JMenuItem();
        menuEmpleado1 = new javax.swing.JMenu();
        verEmpleado = new javax.swing.JMenuItem();
        menuHora = new javax.swing.JMenu();
        menuHoraEntrada = new javax.swing.JMenuItem();
        menuHoraSalida = new javax.swing.JMenuItem();
        consultaDia = new javax.swing.JMenuItem();
        Nómina = new javax.swing.JMenu();
        Consultar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        generaReporteEmpleado = new javax.swing.JMenuItem();
        generaReporteHoras = new javax.swing.JMenuItem();
        generaReporteNomina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaConsulta);

        jLabel1.setText("Seleccione un nombre");

        nombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreBuscarActionPerformed(evt);
            }
        });

        buscFecha.setText("Buscar");
        buscFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscFechaActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Cuántos retardos tuvo?");

        jLabel3.setText("¿Cuántas faltas tiene?");

        jLabel4.setText("Sueldo base");

        jLabel5.setText("Sueldo a pagar");

        txtSueldo.setEditable(false);
        txtSueldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSueldo.setText("1600");
        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar sueldo");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Pagar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        descRetardo.setEditable(false);
        descRetardo.setFocusable(false);

        descFalta.setEditable(false);
        descFalta.setFocusable(false);

        jLabel6.setText("Total de faltas");

        jLabel7.setText("Falta por retardo");

        txtRetardo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        txtFalta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6" }));

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel8.setText("ID");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        menuEmpleado.setText("Inicio");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });

        verPrincipal.setText("Ir a ventana de inicio");
        verPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPrincipalActionPerformed(evt);
            }
        });
        menuEmpleado.add(verPrincipal);

        Menu.add(menuEmpleado);

        menuEmpleado1.setText("Empleado");
        menuEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleado1ActionPerformed(evt);
            }
        });

        verEmpleado.setText("Ir a ventana de empleados");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado1.add(verEmpleado);

        Menu.add(menuEmpleado1);

        menuHora.setText("Hora");

        menuHoraEntrada.setText("Registrar hora de entrada");
        menuHoraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraEntradaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraEntrada);

        menuHoraSalida.setText("Registrar hora de salida");
        menuHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraSalidaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraSalida);

        consultaDia.setText("Consultar horas por día");
        consultaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDiaActionPerformed(evt);
            }
        });
        menuHora.add(consultaDia);

        Menu.add(menuHora);

        Nómina.setText("Nómina");

        Consultar.setText("Consultar nómina por empleado");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Nómina.add(Consultar);

        Menu.add(Nómina);

        jMenu1.setText("Reportes");

        generaReporteEmpleado.setText("Generar reporte de los empleados");
        generaReporteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteEmpleado);

        generaReporteHoras.setText("Generar reporte de horas de entrada y salida");
        generaReporteHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteHorasActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteHoras);

        generaReporteNomina.setText("Generar reporte de nómina");
        generaReporteNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteNominaActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteNomina);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscFecha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addComponent(txtPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRetardo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFalta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSueldo))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descRetardo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(descFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGenerar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscFecha)
                    .addComponent(idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(descRetardo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtRetardo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtFalta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(descFalta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerar)
                            .addComponent(borrar))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnGuardar)
                            .addComponent(txtPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public ArrayList<Empleado> obtenerLista(){
        try {
            String query = "select nombreEmpleado, idEmpleado from empleado";
            Statement stat = cn.createStatement();
            conjuntoResultados = stat.executeQuery(query);
            ArrayList<Empleado> info = new ArrayList<Empleado>();
            if(conjuntoResultados.next()){
                do{
                    Empleado listaTemporal = new Empleado (conjuntoResultados.getString(1), conjuntoResultados.getInt(2));
                    info.add(listaTemporal);
                } while (conjuntoResultados.next());
                return info;
            }else{
                return null;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
            return null;
        }
    }
    
    private void cargarComboBox(){
        ArrayList<Empleado> lista = obtenerLista();
        for(int x=0; x<lista.size(); x++){
            Empleado obj = new Empleado(lista.get(x).getNombreEmpleado(),lista.get(x).getIdEmpleado());
            nombreBuscar.addItem(obj);
        }
    }   
    
    private void verPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPrincipalActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.Principal obj = new VentanaAsistencia.Principal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_verPrincipalActionPerformed

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void menuHoraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraEntradaActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.AltaHoraEntrada obj = new VentanaAsistencia.AltaHoraEntrada();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuHoraEntradaActionPerformed

    private void menuHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraSalidaActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.AltaHoraSalida obj = new VentanaAsistencia.AltaHoraSalida();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuHoraSalidaActionPerformed

    private void nombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreBuscarActionPerformed
        // TODO add your handling code here:
        if(nombreBuscar.getItemCount()>0){
            Empleado empleadoSeleccionado = (Empleado) nombreBuscar.getSelectedItem();
            int id = empleadoSeleccionado.getIdEmpleado();
            String ids = Integer.toString(id);
            idEmpleado.setText(ids);
        }
    }//GEN-LAST:event_nombreBuscarActionPerformed

    private void buscFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscFechaActionPerformed
        // TODO add your handling code here:
        String nombre = nombreBuscar.getSelectedItem().toString();
        cc.ConsultaNombre(nombre, TablaConsulta);
        
    }//GEN-LAST:event_buscFechaActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        int retardos;
        int faltas = 0;
        int faltaTemp;
        int faltaTotal;
        double sueldoTot;
        double sueldoInt;
        int diasTrab;
        double suelDiario;
        try {
            String ret = txtRetardo.getSelectedItem().toString();
            retardos = Integer.parseInt(ret);
            if(retardos>=3&&retardos<=5){
                faltas = faltas + 1;
                String faltaText = String.valueOf(faltas);
                descRetardo.setText(faltaText);
            } else{
                if(retardos==6){
                    faltas = faltas + 2;
                    String faltaText = String.valueOf(faltas);
                    descRetardo.setText(faltaText);
                }
                else{
                String faltaText = String.valueOf(faltas);
                descRetardo.setText(faltaText);
                        }
            }
            String falt = txtFalta.getSelectedItem().toString();
            faltaTemp = Integer.parseInt(falt);
            faltaTotal = faltaTemp + faltas;
            if(faltaTotal>6){
                JOptionPane.showMessageDialog(this, "Las faltas no pueden ser mayores a 6");
            }
            else{
                String faltaText = String.valueOf(faltaTotal);
            descFalta.setText(faltaText);
            String sueldoString = txtSueldo.getText();
            sueldoInt = Double.parseDouble(sueldoString);
            
            suelDiario = sueldoInt/6;
            diasTrab = 6 - faltaTotal;

            sueldoTot = suelDiario * diasTrab;
            sueldoTot = Math.rint(sueldoTot*100)/100;
            
            String sueldoNeto = String.valueOf(sueldoTot);
            txtPagar.setText(sueldoNeto);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No ha llenado todos los campos");
        }
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.ConsultaEmpleado obj = new VentanaAsistencia.ConsultaEmpleado();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void menuEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleado1ActionPerformed

    private void consultaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDiaActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.HoraPorDia obj = new VentanaAsistencia.HoraPorDia();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_consultaDiaActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        txtRetardo.setSelectedIndex(0);
        descRetardo.setText("");
        txtFalta.setSelectedIndex(0);
        descFalta.setText("");
        txtPagar.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.ConsultaNomina obj = new VentanaAsistencia.ConsultaNomina();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement pst = cn.prepareStatement("insert into nomina (sueldoNeto, empleado_idEmpleado) values (?,?)");
            pst.setString(1, txtPagar.getText());
            pst.setString(2, idEmpleado.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Se registró el pago del empleado");
            VentanaAsistencia.ConsultaNomina obj = new VentanaAsistencia.ConsultaNomina();
            obj.setVisible(true);
            dispose();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Se produjo un error, revise que ha generado el sueldo a pagar");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.ConsultaNomina obj = new VentanaAsistencia.ConsultaNomina();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void generaReporteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteEmpleadoActionPerformed
        // TODO add your handling code here:
        Modelo.Conexion cc = new Modelo.Conexion();
        String path = "C://Users/mycomputer/Documents/NetBeansProjects/Asistencias/src/Reportes/reporteEmpleado.jasper";
        JasperReport jr = null;
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cc.getConnection());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Reporte de empleados");

        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_generaReporteEmpleadoActionPerformed

    private void generaReporteHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteHorasActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.BuscarNombre obj = new VentanaAsistencia.BuscarNombre();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_generaReporteHorasActionPerformed

    private void generaReporteNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteNominaActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.BuscarNomina obj = new VentanaAsistencia.BuscarNomina();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_generaReporteNominaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneraNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneraNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneraNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneraNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneraNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Nómina;
    private javax.swing.JTable TablaConsulta;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton buscFecha;
    private javax.swing.JMenuItem consultaDia;
    private javax.swing.JTextField descFalta;
    private javax.swing.JTextField descRetardo;
    private javax.swing.JMenuItem generaReporteEmpleado;
    private javax.swing.JMenuItem generaReporteHoras;
    private javax.swing.JMenuItem generaReporteNomina;
    private javax.swing.JTextField idEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuEmpleado1;
    private javax.swing.JMenu menuHora;
    private javax.swing.JMenuItem menuHoraEntrada;
    private javax.swing.JMenuItem menuHoraSalida;
    private javax.swing.JComboBox nombreBuscar;
    private javax.swing.JComboBox txtFalta;
    private javax.swing.JTextField txtPagar;
    private javax.swing.JComboBox txtRetardo;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JMenuItem verEmpleado;
    private javax.swing.JMenuItem verPrincipal;
    // End of variables declaration//GEN-END:variables
}
