/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaAsistencia;

import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mycomputer
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Ventana principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuEmpleado = new javax.swing.JMenu();
        verEmpleado = new javax.swing.JMenuItem();
        menuHora = new javax.swing.JMenu();
        menuHoraEntrada = new javax.swing.JMenuItem();
        menuHoraSalida = new javax.swing.JMenuItem();
        consultaDia = new javax.swing.JMenuItem();
        Nómina = new javax.swing.JMenu();
        GenerarNomina = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        generaReporteEmpleado = new javax.swing.JMenuItem();
        generaReporteHoras = new javax.swing.JMenuItem();
        generaReporteNomina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido, utilice el menú para navegar por el sistema");

        menuEmpleado.setText("Empleado");
        menuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmpleadoActionPerformed(evt);
            }
        });

        verEmpleado.setText("Ir a ventana de empleados");
        verEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEmpleadoActionPerformed(evt);
            }
        });
        menuEmpleado.add(verEmpleado);

        Menu.add(menuEmpleado);

        menuHora.setText("Hora");

        menuHoraEntrada.setText("Registrar hora de entrada");
        menuHoraEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraEntradaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraEntrada);

        menuHoraSalida.setText("Registrar hora de salida");
        menuHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoraSalidaActionPerformed(evt);
            }
        });
        menuHora.add(menuHoraSalida);

        consultaDia.setText("Consultar horas por día");
        consultaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDiaActionPerformed(evt);
            }
        });
        menuHora.add(consultaDia);

        Menu.add(menuHora);

        Nómina.setText("Nómina");

        GenerarNomina.setText("Consultar nómina");
        GenerarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarNominaActionPerformed(evt);
            }
        });
        Nómina.add(GenerarNomina);

        Menu.add(Nómina);

        jMenu1.setText("Reportes");

        generaReporteEmpleado.setText("Generar reporte de los empleados");
        generaReporteEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteEmpleadoActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteEmpleado);

        generaReporteHoras.setText("Generar reporte de horas de entrada y salida");
        generaReporteHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteHorasActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteHoras);

        generaReporteNomina.setText("Generar reporte de nómina");
        generaReporteNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaReporteNominaActionPerformed(evt);
            }
        });
        jMenu1.add(generaReporteNomina);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEmpleadoActionPerformed

    private void verEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEmpleadoActionPerformed
        // TODO add your handling code here:
        VentanaAsistencia.ConsultaEmpleado obj = new VentanaAsistencia.ConsultaEmpleado();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_verEmpleadoActionPerformed

    private void menuHoraEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraEntradaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.AltaHoraEntrada obj = new VentanaAsistencia.AltaHoraEntrada();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_menuHoraEntradaActionPerformed

    private void menuHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoraSalidaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.AltaHoraSalida obj = new VentanaAsistencia.AltaHoraSalida();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
        
    }//GEN-LAST:event_menuHoraSalidaActionPerformed

    private void consultaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDiaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.HoraPorDia obj = new VentanaAsistencia.HoraPorDia();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_consultaDiaActionPerformed

    private void GenerarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarNominaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.ConsultaNomina obj = new VentanaAsistencia.ConsultaNomina();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_GenerarNominaActionPerformed

    private void generaReporteEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteEmpleadoActionPerformed
        // TODO add your handling code here:
        Modelo.Conexion cc = new Modelo.Conexion();
        String path = "C://Users/mycomputer/Documents/NetBeansProjects/Asistencias/src/Reportes/reporteEmpleado.jasper";
        JasperReport jr = null;
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cc.getConnection());
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle("Reporte de empleados");
            
        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_generaReporteEmpleadoActionPerformed

    private void generaReporteHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteHorasActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.BuscarNombre obj = new VentanaAsistencia.BuscarNombre();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
        
    }//GEN-LAST:event_generaReporteHorasActionPerformed

    private void generaReporteNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaReporteNominaActionPerformed
        // TODO add your handling code here:
        try{
            VentanaAsistencia.BuscarNomina obj = new VentanaAsistencia.BuscarNomina();
            obj.setVisible(true);
            dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Primero debe registrar un empleado");
            JOptionPane.showMessageDialog(this, "Error: Base de datos vacía");
        }
    }//GEN-LAST:event_generaReporteNominaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem GenerarNomina;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Nómina;
    private javax.swing.JMenuItem consultaDia;
    private javax.swing.JMenuItem generaReporteEmpleado;
    private javax.swing.JMenuItem generaReporteHoras;
    private javax.swing.JMenuItem generaReporteNomina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menuEmpleado;
    private javax.swing.JMenu menuHora;
    private javax.swing.JMenuItem menuHoraEntrada;
    private javax.swing.JMenuItem menuHoraSalida;
    private javax.swing.JMenuItem verEmpleado;
    // End of variables declaration//GEN-END:variables
}
